import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Download, Printer, FileCheck, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { caseDeliverableService } from '@/lib/caseDeliverableService';
import DOMPurify from 'dompurify';
import { Loader2 } from 'lucide-react';

const LegalComplaintCaseDeliverable = () => {
  const { intakeId } = useParams();
  const [deliverable, setDeliverable] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDeliverable = async () => {
      try {
        const data = await caseDeliverableService.getCaseDeliverable(intakeId);
        setDeliverable(data);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };
    fetchDeliverable();
  }, [intakeId]);

  const handleDownload = async () => {
    if (deliverable?.file_url) {
      await caseDeliverableService.recordDownload(deliverable.id);
      window.open(deliverable.file_url, '_blank');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) return (
    <div className="min-h-screen bg-[#0A1612] flex items-center justify-center">
      <Loader2 className="w-8 h-8 text-[#E0A995] animate-spin" />
    </div>
  );

  if (!deliverable) return (
    <div className="min-h-screen bg-[#0A1612] flex items-center justify-center text-[#A8B3AF]">
      Deliverable not found or not yet ready.
    </div>
  );

  return (
    <div className="min-h-screen bg-[#f5f5f5] text-[#333] py-10 px-4 print:bg-white print:p-0">
      <div className="max-w-4xl mx-auto">
        {/* Actions Bar - Hidden on Print */}
        <div className="flex justify-between items-center mb-8 print:hidden bg-white p-4 rounded-lg shadow-sm border border-gray-200">
           <div className="flex items-center gap-4">
             <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold uppercase ${
               deliverable.delivery_status === 'delivered' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'
             }`}>
               <FileCheck className="w-4 h-4" />
               {deliverable.delivery_status.replace(/_/g, ' ')}
             </div>
             {deliverable.delivered_at && (
               <span className="text-xs text-gray-500 flex items-center gap-1">
                 <Calendar className="w-3 h-3" /> Delivered: {new Date(deliverable.delivered_at).toLocaleDateString()}
               </span>
             )}
           </div>
           
           <div className="flex gap-2">
             <Button variant="outline" size="sm" onClick={handlePrint}>
               <Printer className="w-4 h-4 mr-2" /> Print
             </Button>
             {deliverable.file_url && (
               <Button onClick={handleDownload} className="bg-[#E0A995] hover:bg-[#D49A89] text-black">
                 <Download className="w-4 h-4 mr-2" /> Download PDF ({(deliverable.file_size / 1024 / 1024).toFixed(1)} MB)
               </Button>
             )}
           </div>
        </div>

        {/* Document Content */}
        <div className="bg-white p-12 shadow-xl print:shadow-none min-h-[1000px]">
          <h1 className="text-3xl font-serif font-bold mb-8 text-center border-b pb-6">{deliverable.case_title}</h1>
          
          <div 
            className="prose max-w-none font-serif text-lg leading-relaxed"
            dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(deliverable.case_content) }} 
          />
          
          <div className="mt-20 pt-8 border-t border-gray-200 text-center text-xs text-gray-400">
            <p>Generated by Movsum Mirzazada Legal Service</p>
            <p>Confidential & Privileged Document</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalComplaintCaseDeliverable;