import html2pdf from 'html2pdf.js';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import CaseDocumentRenderer from '@/components/CaseDocumentRenderer';

export const pdfService = {
  generateCasePDF: async (caseTitle, caseContent) => {
    // Legacy support for simple string content
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="padding: 40px; font-family: 'Times New Roman', serif; color: #333; line-height: 1.6;">
        <div style="text-align: right; margin-bottom: 40px; color: #666; font-size: 12px;">
          Generated by Movsum Mirzazada Legal Service<br>
          ${new Date().toLocaleDateString()}
        </div>
        ${caseContent}
        <div style="margin-top: 50px; border-top: 1px solid #ccc; padding-top: 20px; font-size: 10px; color: #999; text-align: center;">
          © ${new Date().getFullYear()} Movsum Mirzazada. All Rights Reserved. Confidential & Privileged.
        </div>
      </div>
    `;

    return pdfService.processHtmlToPdf(element, caseTitle);
  },

  generateCasePDFFromSchema: async (schema) => {
    try {
      // Use React.createElement to avoid JSX syntax in .js file
      const htmlString = ReactDOMServer.renderToString(
        React.createElement(CaseDocumentRenderer, { schema })
      );
      
      const element = document.createElement('div');
      element.innerHTML = htmlString;
      
      const filename = schema.case_id 
        ? `${schema.case_id}_Complete_Case.pdf` 
        : `Case_${Date.now()}.pdf`;

      return pdfService.processHtmlToPdf(element, filename);
    } catch (error) {
      console.error('Error generating PDF from schema:', error);
      throw new Error('Failed to render case document PDF.');
    }
  },

  processHtmlToPdf: async (element, filename) => {
     const opt = {
      margin: [10, 10, 10, 10], // [top, left, bottom, right]
      filename: filename.replace(/[^a-z0-9\-\.]/gi, '_'),
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, letterRendering: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      const pdfBlob = await html2pdf().set(opt).from(element).output('blob');
      return pdfBlob;
    } catch (error) {
      console.error('PDF Generation failed:', error);
      throw new Error('Failed to generate PDF document.');
    }
  }
};